BEGIN TRANSACTION;
CREATE TABLE 'Advisors' ('id' INTEGER PRIMARY KEY AUTOINCREMENT, 'firstname' VARCHAR(128) NOT NULL, 'lastname' VARCHAR(128) NOT NULL, 'username' VARCHAR(128) NOT NULL, 'password' VARCHAR(128) NOT NULL);
INSERT INTO "Advisors" VALUES(1,'FEVXAIWXLSJJ','AIWXLSJJ','FEVXAIWXLSJJ','QIRRSF19!');
INSERT INTO "Advisors" VALUES(2,'RMIPW','OVS','RMIPWOVS','EHQMR!23');
CREATE TABLE 'Clients' ('id' INTEGER PRIMARY KEY AUTOINCREMENT, 'firstname' VARCHAR(128) NOT NULL, 'lastname' VARCHAR(128) NOT NULL, 'streetname' VARCHAR(128) NOT NULL, 'housenumber' INTEGER NOT NULL, 'zipcode' VARCHAR(128) NOT NULL, 'city' VARCHAR(128) NOT NULL, 'emailaddress' VARCHAR(128) NOT NULL, 'mobilephone' VARCHAR(128) NOT NULL);
CREATE TABLE 'Logging' ('number' INTEGER PRIMARY KEY AUTOINCREMENT, 'username' VARCHAR(128) NOT NULL, 'datetime' VARCHAR(128) NOT NULL, 'description' VARCHAR(128) NOT NULL, 'suspicious' VARCHAR(128) NOT NULL);
INSERT INTO "Logging" VALUES(1,'WY','Fri 5 Oct 2021','data has been added','yes');
INSERT INTO "Logging" VALUES(2,'WY','Fri 5 Oct 2021','data has been added','yes');
INSERT INTO "Logging" VALUES(3,'NOLPEHWJEPHJ','Fri 5 Oct 2021','NOLPEHWJEPHJ logged in with wrong password','yes');
INSERT INTO "Logging" VALUES(4,'NOLPEHWJEPHJ','Fri 5 Oct 2021','lariekoek','yes');
INSERT INTO "Logging" VALUES(5,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(6,'WYTIV','Fri 5 Oct 2021','WYTIV logged in with wrong password','yes');
INSERT INTO "Logging" VALUES(7,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(8,'WYTIV','Fri 5 Oct 2021','WYTIV logged in with wrong password','yes');
INSERT INTO "Logging" VALUES(9,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(10,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(11,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(12,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(13,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(14,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(15,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(16,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(17,'WYTIV','Fri 5 Oct 2021','WYTIV logged in with wrong password','yes');
INSERT INTO "Logging" VALUES(18,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(19,'WYTIV','Fri 5 Oct 2021','WYTIV logged in with wrong password','yes');
INSERT INTO "Logging" VALUES(20,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(21,'WYTIV','Fri 5 Oct 2021','WYTIV logged in with wrong password','yes');
INSERT INTO "Logging" VALUES(22,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(23,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(24,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(25,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(26,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(27,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(28,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(29,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(30,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(31,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(32,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(33,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(34,'WYTIV','Fri 5 Oct 2021','data has been requested','no');
INSERT INTO "Logging" VALUES(35,'ACXMZ','Fri 5 Oct 2021','HEXE LEW FIIR VIUYIWXIH','RS');
CREATE TABLE 'SuperAdmin' ('id' INTEGER PRIMARY KEY AUTOINCREMENT, 'firstname' VARCHAR(128) NOT NULL, 'lastname' VARCHAR(128) NOT NULL, 'username' VARCHAR(128) NOT NULL, 'password' VARCHAR(128) NOT NULL);
CREATE TABLE 'SystemAdmins' ('id' INTEGER PRIMARY KEY AUTOINCREMENT, 'firstname' VARCHAR(128) NOT NULL, 'lastname' VARCHAR(128) NOT NULL, 'username' VARCHAR(128) NOT NULL, 'password' VARCHAR(128) NOT NULL);
INSERT INTO "SystemAdmins" VALUES(1,'WCWXIQ','EHQMR','WCWXIQEHQMR','EHQMR!234');
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('Logging',35);
INSERT INTO "sqlite_sequence" VALUES('Advisors',2);
INSERT INTO "sqlite_sequence" VALUES('SystemAdmins',1);
COMMIT;
